name: iced
channels:
    - default
dependencies:
    - python>3
    - cython
    - numpy>1.16
    - pandas
    - scikit-learn
    - scipy>0.19
    # requirements/test.txt
    - codecov
    - flake8
    - pytest>=5.2
    - pytest-cov>=2.7
