name: iced
channels:
    - default
dependencies:
    - python=3.9
    - pip
    - pip:
        - sphinx
        - numpy
        - scipy
        - matplotlib
        - cython
        - pandas
        - sphinx-gallery
        - numpydoc
