name: Build documentation
on:
  push:
    branches:
      - master
      - main

jobs: 
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Installation of the package
        shell: bash -l {0}
        run: |
            set -ex
            python -m pip install --upgrade pip
            python -m pip install -r requirements/default.txt
            python -m pip install -r requirements/docs.txt
            make install
            set +ex

      - name: Build the documentation
        shell: bash -l {0}
        run: |
            pushd doc
            make html # SPHINXOPTS="-W"
            touch _build/html/.nojekyll
            # See https://github.community/t/github-actions-bot-email-address/17204/5
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions"
            (cd doc && make html)
            cp -r _build/html /tmp/website
            git checkout -b gh-pages
            git rm dev --ignore-unmatch
            cp -r /tmp/website dev
            git add dev
            git commit -m "Deployed to GitHub Pages"
            git push --force --quiet "${GH_REF}" gh-pages
            env:
                GH_REF: git@github.com:hiclib/iced.git
                DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN }}
                GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

      - name: Store docs as artifact
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: doc/_build/html

