name: Build documentation
on:
  push:
    branches:
      - main

jobs:
 
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Installation of the package
        shell: bash -l {0}
        run: |
            set -ex
            python -m pip install --upgrade pip
            python -m pip install -r requirements/default.txt
            python -m pip install -r requirements/doc.txt
            make install
            set +ex

      - name: Run the tests
        shell: bash -l {0}
        run: |
            source .github/workflows/test_script.sh 
            # Now, run the HiC-pro example with the corresponding tests.
            pushd examples/HiC-pro
            bash launch_tests.sh
            popd

      - name: Build the documentation
        shell: bash -l {0}
        run: |
            pushd doc
            make html # SPHINXOPTS="-W"
            touch _build/html/.nojekyll
            eval "$(ssh-agent -s)"
            ssh-add - <<< "${DEPLOY_KEY}"
            # See https://github.community/t/github-actions-bot-email-address/17204/5
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions"
            (cd doc && make html)
            git clone --quiet --branch=gh-pages "${GH_REF}" doc_build
            cd doc_build
            git rm -r dev
            cp -r ../doc/build/html dev
            git add dev
            git commit -m "Deployed to GitHub Pages"
            git push --force --quiet "${GH_REF}" gh-pages
            env:
              GH_REF: git@github.com:hiclib/iced.git
              DEPLOY_KEY: ${{ secrets.DOC_DEPLOY_KEY_PRIVATE }}
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      - name: Store docs as artifact
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: doc/build/html

