name: Run tests
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: 3.8
          environment-file: environment.yml
          activate-environment: iced

      - name: Install the latest version of iced
        shell: bash -l {0}
        run: |
            make install

      # TODO run tests
      - name: Build the documentation
        shell: bash -l {0}
        run: |
            pushd doc
            make html
            touch _build/html/.nojekyll
