name: Run tests
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: 3.8
          environment-file: environment.yml
          activate-environment: iced

      - name: Install the latest version of iced
        shell: bash -l {0}
        run: |
            make install

      # TODO run tests
      - name: Run the tests
        shell: bash -l {0}
        run: |
            # Checking this works…
            make test

            # FIXME
            # And then checking intsalled version which currently fails.
            # mkdir tests-temp
            #pushd tests-temp
            #pytest --showlocals --pyargs --cov=iced --cov-report=xml iced
            #popd
            # Now, run the HiC-pro example with the corresponding tests.
            pushd examples/HiC-pro
            bash launch_tests.sh
            popd

      - name: Build the documentation
        shell: bash -l {0}
        run: |
            pushd doc
            # FIXME let's give up on warnings for now
            make html # SPHINXOPTS="-W"
            touch _build/html/.nojekyll
